#:schema https://json.schemastore.org/ruff.json

extend = ".ruff.toml"

# Enable using ruff with notebooks
include = [ "*.ipynb", "**/pyproject.toml" ]

[lint]
extend-ignore = [ "D", "E402", "N811", "E703", "T201" ]

[lint.isort]
required-imports = [  ]
force-single-line = false
