#:schema https://json.schemastore.org/ruff.json

extend = ".ruff.toml"

[lint]
extend-ignore = ["D", "E402", "F404", "N811", "E703", "T201"]

[lint.isort]
required-imports = []
force-single-line = false
