ignore: []

refactor:
  skip:
    - simplify-boolean-comparison
    - simplify-len-comparison
    - remove-unnecessary-cast
  python_version: "3.10"

metrics:
  quality_threshold: 25.0

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false
