"""Recompute the results of a recorded fit from its input data."""

from __future__ import annotations

import math
from datetime import datetime
from typing import TYPE_CHECKING
from typing import Any
from warnings import warn

import pandas as pd

from glotaran.io import load_parameters
from glotaran.io import load_scheme
from glotaran.model.errors import GlotaranUserError
from glotaran.project.data_summary import compare_data_summaries
from glotaran.project.data_summary import summarize_data
from glotaran.project.export import read_export_files
from glotaran.project.record import RECORD_FILE_NAME
from glotaran.project.record import RecordReference
from glotaran.project.record import collect_environment
from glotaran.project.record import read_record_file
from glotaran.utils.io import load_datasets

if TYPE_CHECKING:
    from pathlib import Path

    from glotaran.project.result import Result
    from glotaran.typing.types import DatasetMappable

DRIFT_RTOL = 1e-6
"""Relative difference of cost and RMSE above which a recompute warns; provisional."""


def recompute(folder: Path, datasets: DatasetMappable, *, allow_data_mismatch: bool) -> Result:
    """Recompute a recorded fit by one evaluation at its optimized parameters.

    Parameters
    ----------
    folder : Path
        Record or export folder.
    datasets : DatasetMappable
        Input data of the fit, regenerated by the user.
    allow_data_mismatch : bool
        Recompute although the data summaries differ from the recorded ones.

    Returns
    -------
    Result
        The recomputed result with ``recomputation`` holding the original fit and the
        reconstruction information.

    Raises
    ------
    GlotaranUserError
        If the record has no optimized parameters, or if the data differ from the recorded data
        and ``allow_data_mismatch`` is ``False``.
    """
    # Of an exported recomputed result: kept so that a chain of recomputes and exports keeps the
    # id and cost history of the original fit
    original_fit: dict[str, Any] = {}
    if (folder / RECORD_FILE_NAME).is_file():
        content = read_record_file(folder)
        record_id = content.get("id")
        files = {
            "scheme": "scheme.yml",
            "initial_parameters": "initial_parameters.csv",
            "optimized_parameters": "optimized_parameters.csv",
        }
    else:
        content, files, original_fit = read_export_files(folder)
        record_id = content.get("record_id") or original_fit.get("id")
    parameters_file = folder / files["optimized_parameters"]
    if not parameters_file.is_file():
        msg = f"The record '{folder}' has no optimized parameters, the fit evaluated no point."
        raise GlotaranUserError(msg)
    dataset_mapping = load_datasets(datasets)
    recorded_data = content.get("data") or {}
    data_differences = [
        difference
        for label, dataset in dataset_mapping.items()
        if label in recorded_data
        for difference in compare_data_summaries(
            label, recorded_data[label], summarize_data(dataset)
        )
    ]
    if data_differences and not allow_data_mismatch:
        msg = (
            f"The data differ from the data of the fit recorded in '{folder}':\n"
            + "\n".join(f"  {difference}" for difference in data_differences)
            + "\nPass allow_data_mismatch=True to recompute anyway."
        )
        raise GlotaranUserError(msg)

    optimized_parameters = load_parameters(parameters_file)
    result = load_scheme(folder / files["scheme"]).optimize(
        optimized_parameters,
        dataset_mapping,
        dry_run=True,
        verbose=False,
        **(content.get("optimizer") or {}),
    )
    result.initial_parameters = load_parameters(folder / files["initial_parameters"])
    if (folder / RECORD_FILE_NAME).is_file():
        result.record = RecordReference(folder.name, folder)

    summary = content.get("summary") or {}
    drift = compare_fit_summaries(summary, result)
    exceeding = [
        f"  {name}: {values['recorded']!r} -> {values['recomputed']!r} "
        + (
            "(not comparable)"
            if values["relative_difference"] is None
            else f"(relative difference {values['relative_difference']:.1e})"
        )
        for name, values in drift.items()
        if values["relative_difference"] is None or values["relative_difference"] > DRIFT_RTOL
    ]
    if exceeding:
        warn(
            f"The recomputed fit differs from the fit recorded in '{folder}':\n"
            + "\n".join(exceeding),
            stacklevel=3,
        )

    cost_history_file = folder / "cost_history.csv"
    result.recomputation = {
        "original_fit": {
            "id": record_id,
            "summary": summary,
            "standard_errors": {
                parameter.label: float(parameter.standard_error)
                for parameter in optimized_parameters.all()
            },
            "cost_history": pd.read_csv(cost_history_file)["cost"].tolist()
            if cost_history_file.is_file()
            else original_fit.get("cost_history", []),
        },
        "reconstruction": {
            "created": datetime.now().astimezone().isoformat(timespec="seconds"),
            "environment": collect_environment(),
            "data_differences": data_differences,
            "drift": drift,
        },
    }
    return result


def compare_fit_summaries(summary: dict[str, Any], result: Result) -> dict[str, dict[str, Any]]:
    """Compare the recorded cost and per-dataset RMSE with those of a recomputed result.

    Parameters
    ----------
    summary : dict[str, Any]
        Summary of the recorded fit.
    result : Result
        Recomputed result.

    Returns
    -------
    dict[str, dict[str, Any]]
        Per value the recorded and recomputed value and their relative difference, which is
        ``None`` if a value is NaN or infinite (not comparable). Values the record does not hold
        are left out.
    """
    pairs = {"cost": (summary.get("cost"), result.optimization_info.cost)}
    for label, recorded in (summary.get("datasets") or {}).items():
        if label in result.optimization_results:
            meta = result.optimization_results[label].meta
            for key in ("root_mean_square_error", "weighted_root_mean_square_error"):
                pairs[f"{label}.{key}"] = (recorded.get(key), getattr(meta, key))
    drift = {}
    for name, values in pairs.items():
        recorded_value, recomputed_value = values
        if recorded_value is None or recomputed_value is None:
            continue
        old, new = float(recorded_value), float(recomputed_value)
        if not (math.isfinite(old) and math.isfinite(new)):
            relative_difference = None
        elif old == new:
            relative_difference = 0.0
        else:
            relative_difference = abs(new - old) / max(abs(old), abs(new))
        drift[name] = {
            "recorded": old,
            "recomputed": new,
            "relative_difference": relative_difference,
        }
    return drift
