name: "Benchmarks"

on:
  pull_request:
  workflow_dispatch:

jobs:
  run_benchmark:
    name: "Run AVS"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install ASV
        run: |
          pip install asv virtualenv
      - name: Create machine-file
        shell: python
        run: |
          from pathlib import Path
          machine_file = Path("/home/runner/.asv-machine.json")
          machine_file_content = '''
          {
            "gh_action": {
              "arch": "x86_64",
              "cpu": "Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz",
              "num_cpu": "2",
              "machine": "gh_action",
              "os": "Linux 5.8.0-1033-azure",
              "ram": "7GB"
            },
            "version": 1
          }'''
          machine_file.write_text(machine_file_content)

      - name: Run PR compare benchmarks
        if: github.event_name == 'pull_request'
        run: |
          pushd benchmark
          asv run main..HEAD --machine gh_action

      - name: Run benchmarks
        if:
          github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
          # asv run 0d41d63ca3ca33bb0b70e25fe76ab0c16f6d2e1d..main --machine gh_action
        run: |
          pushd benchmark
          asv run d57164a65935f66e2821d6938a6ee429694c9762..main --machine gh_action
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: benchmark/.asv/results
